db.payments.insertMany(
    [
        {
            "_id": ObjectId("5ebbc91bb769a64b67f700ea"),
            "requestMetadata": {
                "subscriptionDetails": {
                    "address": {
                        "addressLine": "34 South Hague Drive",
                        "landmark": "Aute architecto nost",
                        "pincode": "560037",
                        "state": "KARNATAKA"
                    },
                    "referenceType": "Inspection Fee",
                    "referenceID": "TC109818",
                    "info": "Hurray",
                    "role": "Training Centre",
                    "name": "Perspiciatis omnis ",
                    "mobileNumber": "9875457456",
                    "emailId": "shila976@gmail.com",
                    "dynamicDetails": {
                        "district": "KOLAR",
                        "tcType": "Government Institute",
                        "tpUserName": "TP049613",
                        "trainingPartner": "zxcvzxcv"
                    }
                },
                "tokenId": "ea4f3519-dc6b-4766-b34f-85e1e5521dba",
                "redirectUrl": "http://13.235.34.143/api/user/v1/receiveTCInpectionpayment/TC109818",
                "amount": "11000",
                "currency": "INR",
                "merchant_id": "107014",
                "customer_id": "TC109818",
                "splitPaymentDetails": []
            },
            "isComplete": true,
            "currency": "INR",
            "isConsumed": true,
            "status": "success",
            "subscriptionId": "ea4f3519-dc6b-4766-b34f-85e1e5521dba",
            "userId": "TC7878789",
            "amount": 11000,
            "sequenceId": "ORD_15146",
            "date": ISODate("2020-05-13T09:30:35.593Z"),
            "billReceiptData": [],
            "__v": 0,
            "responseMetadata": {
                "order_id": "ORD_15146",
                "tracking_id": "309006039779",
                "bank_ref_no": "1589362242598",
                "order_status": "Success",
                "failure_message": "",
                "payment_mode": "Net Banking",
                "card_name": "AvenuesTest",
                "status_code": "null",
                "status_message": "Y",
                "currency": "INR",
                "amount": "11011.80",
                "billing_name": "shila",
                "billing_address": "marathalli",
                "billing_city": "Bangalore",
                "billing_state": "Karnataka",
                "billing_zip": "560037",
                "billing_country": "India",
                "billing_tel": "07425767365",
                "billing_email": "shila8273836@gmail.com",
                "delivery_name": "",
                "delivery_address": "",
                "delivery_city": "",
                "delivery_state": "KARNATAKA",
                "delivery_zip": "560037",
                "delivery_country": "",
                "delivery_tel": "9875457456",
                "merchant_param1": "TC109818",
                "merchant_param2": "",
                "merchant_param3": "",
                "merchant_param4": "",
                "merchant_param5": "",
                "vault": "N",
                "offer_type": "null",
                "offer_code": "null",
                "discount_value": "0.0",
                "mer_amount": "11000.00",
                "eci_value": "null",
                "retry": "N",
                "response_code": "0",
                "billing_notes": "",
                "trans_date": ISODate("2020-05-13T15:00:44Z"),
                "bin_country": "",
                "trans_fee": "10.0",
                "service_tax": "1.8",
                "trans_date_backup": "13/05/2020 15:00:44",
                "conv_fees": 11.8,
                "invoice_no": "INV_309006039779"
            },
            "notification": "Workflow created successfully"
        },
        {
            "_id": ObjectId("5ebbc91bb769a64b67f700fe"),
            "requestMetadata": {
                "subscriptionDetails": {
                    "address": {
                        "addressLine": "34 South Hague Drive",
                        "landmark": "Aute architecto nost",
                        "pincode": "560037",
                        "state": "KARNATAKA"
                    },
                    "referenceType": "CAAF Registration Fee",
                    "referenceID": "TC109818",
                    "info": "Hurray",
                    "role": "Training Centre",
                    "name": "Perspiciatis omnis ",
                    "mobileNumber": "9875457456",
                    "emailId": "shila976@gmail.com",
                    "dynamicDetails": {
                        "district": "KOLAR",
                        "tcType": "Government Institute",
                        "tpUserName": "TP049613",
                        "trainingPartner": "zxcvzxcv"
                    }
                },
                "tokenId": "93e0cfc1-0b1c-4962-bf8d-253f506d0288",
                "redirectUrl": "http://13.235.34.143/api/user/v1/receiveTCRegisterationPayment/TC109818",
                "amount": "3000",
                "currency": "INR",
                "merchant_id": "107014",
                "customer_id": "TC109818",
                "splitPaymentDetails": []
            },
            "isComplete": true,
            "currency": "INR",
            "isConsumed": true,
            "status": "success",
            "subscriptionId": "93e0cfc1-0b1c-4962-bf8d-253f506d0288",
            "userId": "TC7878789",
            "amount": 3000,
            "sequenceId": "ORD_15145",
            "date": ISODate("2020-05-13T09:25:35.759Z"),
            "billReceiptData": [],
            "__v": 0,
            "responseMetadata": {
                "order_id": "ORD_15145",
                "tracking_id": "309006039757",
                "bank_ref_no": "1589361942843",
                "order_status": "Success",
                "failure_message": "",
                "payment_mode": "Net Banking",
                "card_name": "AvenuesTest",
                "status_code": "null",
                "status_message": "Y",
                "currency": "INR",
                "amount": "3011.80",
                "billing_name": "shila",
                "billing_address": "marathalli",
                "billing_city": "Bangalore",
                "billing_state": "Karnataka",
                "billing_zip": "560037",
                "billing_country": "India",
                "billing_tel": "07425767365",
                "billing_email": "shila8273836@gmail.com",
                "delivery_name": "",
                "delivery_address": "",
                "delivery_city": "",
                "delivery_state": "KARNATAKA",
                "delivery_zip": "560037",
                "delivery_country": "",
                "delivery_tel": "9875457456",
                "merchant_param1": "TC109818",
                "merchant_param2": "",
                "merchant_param3": "",
                "merchant_param4": "",
                "merchant_param5": "",
                "vault": "N",
                "offer_type": "null",
                "offer_code": "null",
                "discount_value": "0.0",
                "mer_amount": "3000.00",
                "eci_value": "null",
                "retry": "N",
                "response_code": "0",
                "billing_notes": "",
                "trans_date": ISODate("2020-05-13T14:55:45Z"),
                "bin_country": "",
                "trans_fee": "10.0",
                "service_tax": "1.8",
                "trans_date_backup": "13/05/2020 14:55:45",
                "conv_fees": 11.8,
                "invoice_no": "INV_309006039757"
            },
            "notification": "TC Registration Successfull"
        },
        {
            "_id": ObjectId("5ee3198d69e7425241b445c5"),
            "requestMetadata": {
                "subscriptionDetails": {
                    "address": {
                        "addressLine": "34 South Hague Drive",
                        "landmark": "Aute architecto nost",
                        "pincode": "560037",
                        "state": "KARNATAKA"
                    },
                    "referenceType": "Residential Facility DA Fee",
                    "referenceID": "TC7878789",
                    "info": "Hurray",
                    "role": "Training Centre",
                    "name": "Perspiciatis omnis ",
                    "mobileNumber": "9875457456",
                    "emailId": "shila976@gmail.com",
                    "dynamicDetails": {
                        "district": "KOLAR",
                        "tcType": "Government Institute",
                        "tpUserName": "TP049613",
                        "trainingPartner": "zxcvzxcv"
                    }
                },
                "tokenId": "999d902f-7cdf-4da0-a180-28315a9ae940",
                "redirectUrl": "http://13.235.34.143/api/user/v1/receiveResidentialPayment/TC7878789",
                "amount": "3000",
                "currency": "INR",
                "merchant_id": "107014",
                "customer_id": "TC7878789",
                "splitPaymentDetails": []
            },
            "isComplete": false,
            "currency": "INR",
            "isConsumed": false,
            "status": "failed",
            "subscriptionId": "999d902f-7cdf-4da0-a180-28315a9ae940",
            "userId": "TC7878789",
            "amount": 3000,
            "sequenceId": "ORD_15247",
            "date": ISODate("2020-06-12T05:58:37.957Z"),
            "billReceiptData": [],
            "__v": 0
        },
        {
            "_id": ObjectId("5eecc956dd789f7a86191ec8"),
            "requestMetadata": {
                "subscriptionDetails": {
                    "address": {
                        "addressLine": "34 South Hague Drive",
                        "landmark": "Aute architecto nost",
                        "pincode": "560037",
                        "state": "KARNATAKA"
                    },
                    "referenceType": "Residential Facility Inspection Fee",
                    "referenceID": "TC7878789",
                    "info": "Hurray",
                    "role": "Training Centre",
                    "name": "Perspiciatis omnis ",
                    "mobileNumber": "9875457456",
                    "emailId": "shila976@gmail.com",
                    "dynamicDetails": {
                        "district": "KOLAR",
                        "tcType": "NON PMKK",
                        "tpUserName": "TP049613",
                        "trainingPartner": "zxcvzxcv"
                    }
                },
                "tokenId": "603e8710-bc44-46cb-b59a-42dd4a8acd03",
                "redirectUrl": "http://13.235.34.143/api/user/v1/receive/inspectionpayment/TC7878789",
                "amount": "10000",
                "currency": "INR",
                "merchant_id": "107014",
                "customer_id": "TC7878789",
                "splitPaymentDetails": []
            },
            "isComplete": true,
            "currency": "INR",
            "isConsumed": true,
            "status": "pending",
            "subscriptionId": "603e8710-bc44-46cb-b59a-42dd4a8acd03",
            "userId": "TC7878789",
            "amount": 10000,
            "sequenceId": "ORD_15300",
            "tid": 153008,
            "date": ISODate("2020-06-19T14:19:02.876Z"),
            "billReceiptData": [],
            "__v": 0,
            "responseMetadata": {
                "order_id": "ORD_15300",
                "tracking_id": "309006131677",
                "bank_ref_no": "1592576348637",
                "order_status": "Success",
                "failure_message": "",
                "payment_mode": "Net Banking",
                "card_name": "AvenuesTest",
                "status_code": "null",
                "status_message": "Y",
                "currency": "INR",
                "amount": "10011.80",
                "billing_name": "shila",
                "billing_address": "marathalli",
                "billing_city": "Bangalore",
                "billing_state": "Karnataka",
                "billing_zip": "560037",
                "billing_country": "India",
                "billing_tel": "07425767365",
                "billing_email": "shila8273836@gmail.com",
                "delivery_name": "",
                "delivery_address": "",
                "delivery_city": "",
                "delivery_state": "KARNATAKA",
                "delivery_zip": "560037",
                "delivery_country": "",
                "delivery_tel": "9875457456",
                "merchant_param1": "TC7878789",
                "merchant_param2": "",
                "merchant_param3": "",
                "merchant_param4": "",
                "merchant_param5": "",
                "vault": "N",
                "offer_type": "null",
                "offer_code": "null",
                "discount_value": "0.0",
                "mer_amount": "10000.00",
                "eci_value": "null",
                "retry": "N",
                "response_code": "0",
                "billing_notes": "",
                "trans_date": ISODate("2020-06-19T19:49:32Z"),
                "bin_country": "",
                "trans_fee": "10.0",
                "service_tax": "1.8",
                "trans_date_backup": "19/06/2020 19:49:32",
                "conv_fees": "11.80",
                "invoice_no": "INV_309006131677"
            }
        },
    ])